### ISSUE TITLE
Pressing "Cancel" in the colour picker saves the colour as #000000

### ISSUE THREAD

**Issue by HanPrower** [kostoskistefan/hoverclock-qt#12]
As the title says the "Cancel" button isn't just closing the picker, it's choosing #000000 instead.

**Comment by kostoskistefan** [comment]
The issue is resolved on the main branch, thanks for submitting. The AppImage will probably updated tomorrow.

**Comment by kostoskistefan** [comment]
I've updated the AppImage with the fix for this issue.
