### ISSUE TITLE
Info for setting manual time

### ISSUE THREAD

**Issue by docop** [kostoskistefan/hoverclock-qt#15]
Hi  so the app look very great and especially in appimage. I do wonder, can it be possible to have a setting to make the time in manual mode ?  As to set our own time we want ?  like to have the system clock at x time and  hoverclock set to a different region time.
Thanks in advance

**Comment by kostoskistefan** [comment]
Hey, @docop! Thanks for submitting a great suggestion.

It's possible to do it, although I can think of 2 different ways of doing it:
* Set the time manually by setting both the hours and minutes in a text box in the settings dialog; or
* Choosing a timezone and displaying the corresponding time.

Personally, I think that the second option might be more useful to people, so I will implement that first, but I'm not completely disregarding the other option.

Once the feature is implemented, I'll close this issue.

**Comment by docop** [comment]
Oh, indeed, if timezone is easier, yes that can be best. like having direct Utc can be cool.  Will it be local or a need for connection to a timeserver also needed for ?

**Comment by kostoskistefan** [comment]
I'm trying to use as few dependencies as possible, so it will be local, but daylight saving time will still be supported.

As specified in the [QTimeZone class](https://doc.qt.io/qt-5/qtimezone.html):
> This class provides a stateless calculator for time zone conversions between UTC and the local time in a specific time zone. By default it uses the host system time zone data to perform these conversions.

**Comment by kostoskistefan** [comment]
I've implemented the requested feature. I've updated the releases section and the AUR package, so feel free to check it out.

Once again, thank you for the suggestion, I appreciate it! :smile:

**Comment by docop** [comment]
Hi  So yeah, quite terrific! it's quite good. As for improved you asked, what i see is the taskbar icon : with the toggle visibility.. perhaps making the circle a dim red. Like when on, the same current dim gray, but when we toggle visibily to turn off : have the circle red (dim red or dark red...)

 And perhaps another point, don't know if that easy.. The block list: have an option to list the current opened soft.. or a soft picker.. Like in xfce, when you click something, the menu appear to ask to open with what. Perhaps a kind of call to get the same idea of a menu and pick the soft to exclude directly from that.. ? Or a picker.. as how we add other appimage soft ?
thanks

**Comment by kostoskistefan** [comment]
Please open a new issue with the same suggestions/questions, because they are not directly connected to this particular issue. Thank you for understanding!
