### ISSUE TITLE
Deselect Date doesn't resize container

### ISSUE THREAD

**Issue by HanPrower** [kostoskistefan/hoverclock-qt#2]
First, nice app :smile: 

If you deselect to show the date the date will disappear but the container won't respond to it being removed (i.e. the height/padding).

**Comment by kostoskistefan** [comment]
First, thank you @HanFox! :smile:

That's a really good catch. Thank you for the great suggestion. I'll add it to my todo list and i'll implement it soon. 

After doing so, I'll mark this issue as closed.

**Comment by kostoskistefan** [comment]
I updated the window resizing code, it should be fixed now. I added a new version to the release section, feel free to check it out.

Thank you for contributing!
