### ISSUE TITLE
version `Qt_5.15' not found

### ISSUE THREAD

**Issue by tiagofrancafernandes** [kostoskistefan/hoverclock-qt#22]
```
/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /home/tiago/Hoverclock/bin/hoverclock)
```

On Ubuntu 20.04 I found only v12 `5.12.8+dfsg-0ubuntu2.1`.

```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```

Install by .run file (tried via .deb before)

**Comment by tiagofrancafernandes** [comment]
Sorry, just need run the `.sh`
I had done this before but nothing appeared on the screen. the reason is that it was transparent.
I just need to open the binary with the `-c` parameter and adjust the opacity to something readable.

I do:
`/home/tiago/Hoverclock/hoverclock.sh -c`

![image](https://user-images.githubusercontent.com/8310974/168518963-40d754c9-b923-4dd0-9e29-77e29d9e9f1e.png)

**Comment by kostoskistefan** [comment]
The `hoverclock.sh` file contains the environment variables needed to use the statically linked QT version that comes with the software. If you run the binary directly, it tries to use the locally installed version of QT including all the dependencies (which may or may not be installed on your system), but I'm glad you got that sorted out. 

Although I'm not sure why the opacity was all the way down. By default it is set to 0.5 unless it has been modified in the config file before running the app. Anyhow, the `-c` parameter was a great way to debug and solve the problem.

There will be more updates and bug fixes in the near future. I hope you find the software useful!
