### ISSUE TITLE
Font / Stroke colour choosers act peculiarly

### ISSUE THREAD

**Issue by HanPrower** [kostoskistefan/hoverclock-qt#7]
1) When you open the colour picker it will always default to #ffffff regardless of the colour saved.

2) If you select a Fill Colour, the Stroke Colour option will be changed, but the next time you open the Options dialogue the colours will be correct. The actual colours in the overlay will also be applied correctly. Modifying the Stroke Colour doesn't suffer this issue.

**Comment by kostoskistefan** [comment]
1. This was an easy fix. I forgot to implement it. Thank you for noticing and reporting it.
2. I made a typo, should be fixed now.

I'll update the release soon.
