### ISSUE TITLE
Font style chooser opens with the wrong settings

### ISSUE THREAD

**Issue by HanPrower** [kostoskistefan/hoverclock-qt#8]
Regardless of the option saved when next the Select Font dialogue is opened it always defaults to Sans Serif, Normal, 9.

**Comment by kostoskistefan** [comment]
Same as the color dialog mentioned in issue #7. It should be fixed now.

Again, thank you for testing the software and contributing! I greatly appreciate it.

**Comment by HanPrower** [comment]
> Again, thank you for testing the software and contributing! I greatly appreciate it.

No worries. It's such a useful app I'm happy to help :smiley:
